################ English language ##################
[en]
languageName = "Engish"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[vn]
languageName = "Vietnamese"
languageCode = "vi"
contentDir = "content/vn"
weight = 1
